// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_api_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *GetHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_api_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TransType     string                 `protobuf:"bytes,5,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TransHash     string                 `protobuf:"bytes,7,opt,name=trans_hash,json=transHash,proto3" json:"trans_hash,omitempty"`
	FromUserId    int64                  `protobuf:"varint,8,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,9,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetTransHash() string {
	if x != nil {
		return x.TransHash
	}
	return ""
}

func (x *Transaction) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Transaction) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AddTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TransType     string                 `protobuf:"bytes,4,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransHash     string                 `protobuf:"bytes,6,opt,name=trans_hash,json=transHash,proto3" json:"trans_hash,omitempty"`
	FromUserId    int64                  `protobuf:"varint,7,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,8,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTransactionRequest) Reset() {
	*x = AddTransactionRequest{}
	mi := &file_api_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransactionRequest) ProtoMessage() {}

func (x *AddTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransactionRequest.ProtoReflect.Descriptor instead.
func (*AddTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *AddTransactionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddTransactionRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *AddTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddTransactionRequest) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *AddTransactionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AddTransactionRequest) GetTransHash() string {
	if x != nil {
		return x.TransHash
	}
	return ""
}

func (x *AddTransactionRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *AddTransactionRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type AddTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTransactionResponse) Reset() {
	*x = AddTransactionResponse{}
	mi := &file_api_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransactionResponse) ProtoMessage() {}

func (x *AddTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransactionResponse.ProtoReflect.Descriptor instead.
func (*AddTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *AddTransactionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_proto_transaction_proto protoreflect.FileDescriptor

const file_api_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/transaction.proto\x12\abalance\",\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x12GetHistoryResponse\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.balance.TransactionR\ftransactions\"\x99\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"trans_type\x18\x05 \x01(\tR\ttransType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"trans_hash\x18\a \x01(\tR\ttransHash\x12 \n" +
	"\ffrom_user_id\x18\b \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\t \x01(\x03R\btoUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xf4\x01\n" +
	"\x15AddTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"trans_type\x18\x04 \x01(\tR\ttransType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"trans_hash\x18\x06 \x01(\tR\ttransHash\x12 \n" +
	"\ffrom_user_id\x18\a \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\b \x01(\x03R\btoUserId\"(\n" +
	"\x16AddTransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xb5\x01\n" +
	"\x19TransactionHistoryService\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.balance.GetHistoryRequest\x1a\x1b.balance.GetHistoryResponse\x12Q\n" +
	"\x0eAddTransaction\x12\x1e.balance.AddTransactionRequest\x1a\x1f.balance.AddTransactionResponseB\x18Z\x16crypto_exchange/api/pbb\x06proto3"

var (
	file_api_proto_transaction_proto_rawDescOnce sync.Once
	file_api_proto_transaction_proto_rawDescData []byte
)

func file_api_proto_transaction_proto_rawDescGZIP() []byte {
	file_api_proto_transaction_proto_rawDescOnce.Do(func() {
		file_api_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_transaction_proto_rawDesc), len(file_api_proto_transaction_proto_rawDesc)))
	})
	return file_api_proto_transaction_proto_rawDescData
}

var file_api_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_transaction_proto_goTypes = []any{
	(*GetHistoryRequest)(nil),      // 0: balance.GetHistoryRequest
	(*GetHistoryResponse)(nil),     // 1: balance.GetHistoryResponse
	(*Transaction)(nil),            // 2: balance.Transaction
	(*AddTransactionRequest)(nil),  // 3: balance.AddTransactionRequest
	(*AddTransactionResponse)(nil), // 4: balance.AddTransactionResponse
}
var file_api_proto_transaction_proto_depIdxs = []int32{
	2, // 0: balance.GetHistoryResponse.transactions:type_name -> balance.Transaction
	0, // 1: balance.TransactionHistoryService.GetHistory:input_type -> balance.GetHistoryRequest
	3, // 2: balance.TransactionHistoryService.AddTransaction:input_type -> balance.AddTransactionRequest
	1, // 3: balance.TransactionHistoryService.GetHistory:output_type -> balance.GetHistoryResponse
	4, // 4: balance.TransactionHistoryService.AddTransaction:output_type -> balance.AddTransactionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_transaction_proto_init() }
func file_api_proto_transaction_proto_init() {
	if File_api_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_transaction_proto_rawDesc), len(file_api_proto_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_transaction_proto_goTypes,
		DependencyIndexes: file_api_proto_transaction_proto_depIdxs,
		MessageInfos:      file_api_proto_transaction_proto_msgTypes,
	}.Build()
	File_api_proto_transaction_proto = out.File
	file_api_proto_transaction_proto_goTypes = nil
	file_api_proto_transaction_proto_depIdxs = nil
}
